version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment: 
      POSTGRES_DB: ${POSTGRES_DB:-tradedb}
      POSTGRES_USER: ${POSTGRES_USER:-trade}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tradepw}

    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment: 
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-trade}:${POSTGRES_PASSWORD:-tradepw}@db:5432/${POSTGRES_DB:-tradedb}
      SEED_ON_START: "true"
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8443
      SSL_CERT_FILE: /certs/cert.pem
      SSL_KEY_FILE: /certs/key.pem
    volumes:
      - ./certs:/certs
    ports:
      - "8443:8443" # HTTPS
    command: ["/bin/sh","/app/entrypoint.sh"]

volumes:
  db-data:



