"""rename custumer_id to customer_id

Revision ID: 590db5e6ec0e
Revises: 
Create Date: 2025-10-16 15:42:23.060536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590db5e6ec0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.drop_constraint('documents_custumer_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'customers', ['customer_id'], ['id'])
    op.drop_column('documents', 'custumer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('custumer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_custumer_id_fkey', 'documents', 'customers', ['custumer_id'], ['id'])
    op.drop_column('documents', 'customer_id')
    # ### end Alembic commands ###
